Add missing env for werf release
Without this env, the `yq` command is not working

```
Error: unable to generate default repo: unable to load werf config: template: werfConfig:8:3: executing "werfConfig" at <tpl (.Files.Get ".werf/stages/release.yaml") $>: error calling tpl: template: 81fd9x7m82:12:23: executing "81fd9x7m82" at <env "MODULES\_MODULE\_TAG">: error calling env: the environment variable "MODULES\_MODULE\_TAG" must be set or default must be provided

[15](https://github.com/dmitrpopkov/acceptance-test/actions/runs/11517318212/job/32061756457#step:5:17)/home/runner/work/\_temp/79df120e-8940-41a6-911b-6c82466a4f08.sh: line 1: : No such file or directory
```

Signed-off-by: Ruslan Usmanov <114342765+haosb@users.noreply.github.com>